packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  '@mdi/font': ^7.4.47
  '@tanstack/vue-query': ^5.103.1
  '@types/node': ^24
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@1.1.0
  vite-plus: 1.1.0
overrides:
  vite@*: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
allowBuilds:
  esbuild: true
  vue-demi: true
minimumReleaseAgeExclude:
  - tsx@4.23.14
  - '@voidzero-dev/vite-plus-core@1.1.0'
  - '@voidzero-dev/vite-plus-darwin-arm64@1.1.0'
  - '@voidzero-dev/vite-plus-darwin-x64@1.1.0'
  - '@voidzero-dev/vite-plus-linux-arm64-gnu@1.1.0'
  - '@voidzero-dev/vite-plus-linux-arm64-musl@1.1.0'
  - '@voidzero-dev/vite-plus-linux-x64-gnu@1.1.0'
  - '@voidzero-dev/vite-plus-linux-x64-musl@1.1.0'
  - '@voidzero-dev/vite-plus-win32-arm64-msvc@1.1.0'
  - '@voidzero-dev/vite-plus-win32-x64-msvc@1.1.0'
  - vite-plus@1.1.0
